on.get(function () {
    throw new Error('exception')
})
